### PR TITLE
Localization of plugin settings

### PR DESCRIPTION
**Pull request by Axialer**
PRs: Localization of plugin settings
============================

Before writing anything about your changes in this PR, checklist this items:

- [x] Agreed with current version of [code of conduct](./../CODE_OF_CONDUCT.md).
- [x] Read and followed current version of [“issue policy”](./../../docs/github/ISSUES/ISSUE_POLICY.md).
- [x] Read and followed current version of [“commit convention”](./../../docs/github/COMMIT_CONVENTION.md).

By agreeding and following this project's documentation, you are reminded that your's commit and styling of changes must follow this project's documentation, in case of “de-followization”, there are two ways before you make sure to publishing your PR:

1. In case of “de-followization” of commit's styling convention, you can amend them (change their message and description signatures):

```powershell
git commit --amend -m "MESSAGE" -m "DESCRIPTION"
```

For amending old commit, see the stackoverflow question[^1], more about changing commits in official docs for github: \
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message/

[^1]: https://stackoverflow.com/questions/17338792/amending-old-commit/

2. In case of “de-followization” of coding, documentation and etc. files, you can just refactor everything you need by following styling guidelines of project.

### Changes with that PR

**Changes in the ru.ts file responsible for localization of plugin settings**

### Process of testing for that PR

- Was testing process initiated via this PR?\
  answer (y/n): (n);
- If testing was done, type below the procedures you make: \
  ...

### Additional context for that PR

...

### CODE REVIEW

**Comment by Axialer** [comment]
> # PRs: Localization of plugin settings
> Before writing anything about your changes in this PR, checklist this items:
> 
> * [x]  Agreed with current version of [code of conduct](./../CODE_OF_CONDUCT.md).
> * [x]  Read and followed current version of [“issue policy”](./../../docs/github/ISSUES/ISSUE_POLICY.md).
> * [x]  Read and followed current version of [“commit convention”](./../../docs/github/COMMIT_CONVENTION.md).
> 
> By agreeding and following this project's documentation, you are reminded that your's commit and styling of changes must follow this project's documentation, in case of “de-followization”, there are two ways before you make sure to publishing your PR:
> 
> 1. In case of “de-followization” of commit's styling convention, you can amend them (change their message and description signatures):
> 
> ```powershell
> git commit --amend -m "MESSAGE" -m "DESCRIPTION"
> ```
> 
> For amending old commit, see the stackoverflow question[1](#user-content-fn-1-3fbeb154a516065de39e36f6831e445a), more about changing commits in official docs for github: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message/
> 
> 2. In case of “de-followization” of coding, documentation and etc. files, you can just refactor everything you need by following styling guidelines of project.
> 
> ### Changes with that PR
> Please, write below every changes you made: **Changes in the ru.ts file responsible for localization of plugin settings**
> 
> ### Process of testing for that PR
> * Was testing process initiated via this PR?
>   answer (y/n): (n);
> * If testing was done, type below the procedures you make: 
>   ...
> 
> ### Additional context for that PR
> ...
> 
> ## Footnotes
> 1. https://stackoverflow.com/questions/17338792/amending-old-commit/ [↩](#user-content-fnref-1-3fbeb154a516065de39e36f6831e445a)

**Comment by angelomira** [comment]
I worked on translating this plugin myself, so I want to "put my two cents in" to this joint effort:

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L36
I think "Advanced block" can be translated into the "Продвинутый блок" (in rus. "advanced" equals to "продвинутый"):
потому что _advanced_ используется обычно в терминологии как _"продвинутого"_, а не расширенного, хоть и второй смысл так же имеет место быть, он очень контекстуальный.

**Источник:** https://dictionary.cambridge.org/dictionary/english/advanced

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L51

"disables markdown from OBSIDIAN's registry" is not equals "отключает Markdown-файлы из реестра OBSIDIAN.", in translation it is stated in plural, while original is in singular.

В оригинале упоминается расширение как формат в единственном числе, я думаю можно оставить такую разметку просто как Markdown и в переводе, потому что иначе остаётся место для свободомыслия там, где это не надо.

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L55

Ошибка в "используйте `е` осторожностью" (заменить "е" на "с").

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L63

В оригинале упоминается ["editors enabling extension's view in OBSIDIAN app."](https://github.com/Falcion/UNITADE.md/pull/81/commits/06b9f1a4974d9e00b8756ae32ad03f73f5a75144#), что можно скорее перевести как "позволяет", а не включает, здесь необходим дословный перевод, сомневаюсь что автор имел в виду конкретно включение (хотя можно и его спросить).

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L103

Не "пустых файлов", а файлов без расширения, небольшой докоп, но всё-таки файлы без расширений и пустые файлы это немного разные вещи, даже в смысле перевода слово "bare" можно перевести как "голое", нежели пустое.

**Источник:** https://dictionary.cambridge.org/dictionary/english/bare

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L117

Тут упущение информации и вследствие этого неправильная формулировка (ИМХО):

`"Reloads views and registries extensions providing new settings and data to the app and keeping experience up-to-date with config."`

Можно перевести скорее как:
`"Перезагружает представления и реестры расширения, добавляя новые настройки и данные в приложение, поддерживая актуальность настроек плагина с приложением."`

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L140

Здесь проблема на стороне разработчика, ибо режим по умолчанию включен, я хочу по этому поводу сделать отдельный топик, либо может быть сразу его здесь и обсудить.

@Falcion, in your plugin UNITADE it is stated that compatibility module is turned off by default, while in practice it is turned on by default: how do we interpret this in our translations? Provide us some details for this case please.

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L147

Моя личная придирка (опять же, ИМХО), но вики есть вики, документация как-то неуместна, если бы разработчик имел в виду документацию, мог бы и "docs" написать.

Отсюда идёт кстати и проблема, там уже не "описание", а "документация" плагина, т.е. так мы исправляем тафталогию и переносим правильно смысл (речь идёт об `"При нажатии происходит переход на страницу документации проекта на GitHub, которая содержит описание плагина."`).

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L182

Лучше стандартные, разраб использует формулировку "простых" как стандартных (настройка "расширения" по-русски): видимо его стилизация, но смысл такой.

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L228

Важное упущение, в оригинале присутствует кусочек "AS", который говорит что расширения в таком случае будут обрабатываться не как код, а как Markdown-разметка.

Аналогичный тезис и [здесь](https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L230), здесь говорится не просто о модулях, а о том КАК расширения будут вести себя при включении этих функций.

**Comment by Falcion** [comment]
@angelomira, indeed, compatibility module is enabled by default, I would remain this feature as it is and change "settings description" from now on, thanks!

@Axialer as I understood from context, compatibility module is TURNED ON by default, NOT TURNED OFF.

Thanks for your contributions!

**Comment by angelomira** [comment]
@Falcion, no problem!

Значит реально ошибка на стороне разработчика, @Axialer, там должно быть по умолчанию включено (в модуле совместимости):

https://github.com/Falcion/UNITADE.md/blob/06b9f1a4974d9e00b8756ae32ad03f73f5a75144/source/locales/langs/ru.ts#L140

**Review by Falcion — CHANGES_REQUESTED** [review]
Read:
https://github.com/Falcion/UNITADE.md/pull/81#issuecomment-2491105245

**Comment by Axialer** [comment]
@angelomira, Я внес правки в перевод плагина. Спасибо за помощь! Если есть возможно, прошу проверить мой перевод ещё раз, для улучшения его качества.

Касательно модуля совместимости - я не вносил изменений так как данное пояснение подходит как в случае если данный модуль включен, так и когда он выключен (как мне кажется).

**Comment by Falcion** [comment]
While everything looks "alright," please check your commits naming, follow "commits naming convention", you can read about it here:
["Commit convention"](https://github.com/Falcion/UNITADE.md/blob/main/docs-markdown/github/COMMIT_CONVENTION.md)

**Review by Falcion — APPROVED** [review]
Reviewed by @angelomira, thanks for his help, commit convention styling now is implemented.

Build-test was provided by myself on my machine, plugin works.

**Pull request merged**
